/**
 * Exercise names for autocomplete — aligns with aliases in built-in-exercise-images.ts.
 * Covers barbell / dumbbell / cable / machine / single-arm / single-leg variants where common.
 */
const RAW_EXERCISES: string[] = [
  // ——— Chest ———
  "Arnold Press",
  "Barbell Bench Press",
  "Bench Press",
  "Cable Chest Fly",
  "Cable Chest Press",
  "Cable Fly",
  "Cable Fly High",
  "Cable Fly Low",
  "Chest Fly",
  "Chest Fly Machine",
  "Chest Press",
  "Chest Press Machine",
  "Close Grip Bench Press",
  "Close Grip Push Up",
  "Decline Dumbbell Bench Press",
  "Decline Dumbbell Fly",
  "Dips",
  "Dumbbell Bench Press",
  "Dumbbell Chest Fly",
  "Dumbbell Fly",
  "Flat Dumbbell Bench Press",
  "Hex Press",
  "Incline Barbell Bench Press",
  "Incline Bench Press",
  "Incline Cable Fly",
  "Incline Chest Press Machine",
  "Incline Dumbbell Bench Press",
  "Incline Dumbbell Fly",
  "Incline Dumbbell Press",
  "Incline Smith Machine Press",
  "Landmine Press",
  "Low Cable Fly",
  "Push Ups",
  "Smith Machine Bench Press",
  "Standing Cable Fly",
  "Svend Press",
  "Wide Grip Bench Press",

  // ——— Back ———
  "Assisted Pull Up",
  "Back Extension",
  "Barbell Row",
  "Barbell Shrug",
  "Cable Pullover",
  "Dumbbell Pullover",
  "Chest Supported Row",
  "Deadlift",
  "Dumbbell Row",
  "Face Pull",
  "Hyperextension",
  "Inverted Row",
  "Lat Pulldown",
  "Lat Pull Overs",
  "Low Cable Row",
  "Machine High Row",
  "Machine Low Row",
  "Machine Row",
  "Neutral Grip Lat Pulldown",
  "One Arm Cable Row",
  "One Arm Dumbbell Row",
  "One Arm Lat Pulldown",
  "Pull Ups",
  "Rear Delt Fly",
  "Rope Pull Down",
  "Seated Cable Row",
  "Seated Row Machine",
  "Shrugs",
  "Single Arm Cable Pulldown",
  "Single Arm Cable Row",
  "Single Arm Dumbbell Row",
  "Single Arm Lat Pulldown",
  "Straight Arm Cable Pulldown",
  "Straight Arm Lat Pulldown",
  "Sumo Deadlift",
  "T-Bar Row",
  "Trap Bar Deadlift",
  "Upright Row",
  "Wide Grip Lat Pulldown",

  // ——— Shoulders ———
  "Behind Neck Press",
  "Cable Front Raise",
  "Cable Lateral Raise",
  "Cable Rear Delt Fly",
  "Cable Upright Row",
  "Dumbbell Front Raise",
  "Dumbbell Lateral Raise",
  "Dumbbell Rear Delt Fly",
  "Dumbbell Shoulder Press",
  "Front Raises",
  "Landmine Shoulder Press",
  "Lateral Raise Single Arm",
  "Lateral Raises",
  "Machine Lateral Raise",
  "Machine Shoulder Press",
  "Military Press",
  "Overhead Press",
  "Rear Delt Fly Machine",
  "Seated Shoulder Press Machine",
  "Shoulder Press",
  "Smith Machine Shoulder Press",

  // ——— Biceps ———
  "Barbell Curl",
  "Bayesian Curl",
  "Bicep Curl",
  "Cable Curl",
  "Concentration Curl",
  "Cross Body Hammer Curl",
  "Drag Curl",
  "Dumbbell Curl",
  "EZ Bar Curl",
  "Hammer Curl",
  "Incline Dumbbell Curl",
  "Machine Curl",
  "One Arm Cable Curl",
  "One Arm Dumbbell Curl",
  "One Arm Preacher Curl",
  "Preacher Curl",
  "Reverse Curl",
  "Single Arm Cable Curl",
  "Spider Curl",
  "Zottman Curl",

  // ——— Triceps ———
  "Cable Overhead Extension",
  "Cable Tricep Pushdown",
  "Close Grip Bench Press",
  "Diamond Push Up",
  "Dips",
  "Kickbacks",
  "Lying Tricep Extension",
  "Machine Dip",
  "One Arm Cable Pushdown",
  "One Arm Overhead Extension",
  "One Handed Tricep Push Down",
  "Overhead Tricep Extensions",
  "Rope Pushdown",
  "Skull Crushers",
  "Single Arm Cable Kickback",
  "Tricep Dips",
  "Tricep Extension",
  "Tricep Pushdown",

  // ——— Legs ——— quads / compound
  "Barbell Front Squat",
  "Barbell Squat",
  "Box Squat",
  "Bulgarian Split Squat",
  "Goblet Squat",
  "Hack Squat",
  "Hack Squat Machine",
  "Landmine Squat",
  "Leg Extension",
  "Leg Extension Machine",
  "Leg Press",
  "Leg Press Machine",
  "Pendulum Squat",
  "Sissy Squat",
  "Squat",

  // ——— Hamstrings / glutes ———
  "Glute Bridge",
  "Good Morning",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Hip Thrust",
  "Hyperextension",
  "Leg Curl",
  "Leg Curl Machine",
  "Lying Leg Curl",
  "Romanian Deadlift",
  "Seated Leg Curl",
  "Stiff Leg Deadlift",

  // ——— Lunges / unilateral legs ———
  "Curtsy Lunge",
  "Deficit Lunge",
  "Dumbbell Lunge",
  "Forward Lunge",
  "Lateral Lunge",
  "Lunges",
  "Reverse Lunge",
  "Split Squat",
  "Walking Lunges",

  // ——— Calves ———
  "Calf Raise",
  "Donkey Calf Raise",
  "Seated Calf Raise",
  "Standing Calf Raise",

  // ——— Core / misc ———
  "Ab Wheel Rollout",
  "Cable Crunch",
  "Hanging Leg Raise",
  "Plank",
  "Russian Twist",
  "Side Plank",
];

function normalizeDedupe(names: string[]): string[] {
  const seen = new Map<string, string>();
  for (const n of names) {
    const t = n.trim();
    if (!t) continue;
    const low = t.toLowerCase();
    if (!seen.has(low)) seen.set(low, t);
  }
  return [...seen.values()].sort((a, b) => a.localeCompare(b));
}

export const EXERCISE_SUGGESTIONS: string[] = normalizeDedupe(RAW_EXERCISES);

export function filterExerciseSuggestions(query: string, limit = 15): string[] {
  if (!query.trim()) return EXERCISE_SUGGESTIONS.slice(0, limit);
  const q = query.toLowerCase().trim();
  return EXERCISE_SUGGESTIONS.filter((name) => name.toLowerCase().includes(q)).slice(0, limit);
}
