/**
 * Exercise names for autocomplete — aligns with aliases in built-in-exercise-images.ts.
 * Covers barbell / dumbbell / cable / machine / single-arm / single-leg variants where common.
 */
const RAW_EXERCISES: string[] = [
  // ——— Chest ———
  "Arnold Press",
  "Barbell Bench Press",
  "Bench Press",
  "Cable Chest Fly",
  "Cable Chest Press",
  "Cable Crossover",
  "Cable Fly",
  "Cable Fly High",
  "Cable Fly Low",
  "Chest Fly",
  "Chest Fly Machine",
  "Chest Press",
  "Chest Press Machine",
  "Chest Supported Row",
  "Close Grip Bench Press",
  "Close Grip Push Up",
  "Decline Bench Press",
  "Decline Cable Fly",
  "Decline Chest Press Machine",
  "Decline Dumbbell Bench Press",
  "Decline Dumbbell Fly",
  "Decline Smith Press",
  "Dips",
  "Dumbbell Bench Press",
  "Dumbbell Chest Fly",
  "Dumbbell Fly",
  "Dumbbell Pullover",
  "Flat Bench Cable Fly",
  "Flat Dumbbell Bench Press",
  "Flat Dumbbell Fly",
  "Hex Press",
  "Incline Barbell Bench Press",
  "Incline Bench Press",
  "Incline Cable Fly",
  "Incline Chest Fly Machine",
  "Incline Chest Press Machine",
  "Incline Dumbbell Bench Press",
  "Incline Dumbbell Fly",
  "Incline Dumbbell Press",
  "Incline Smith Machine Press",
  "Landmine Press",
  "Low Cable Fly",
  "Machine Bench Press",
  "Machine Chest Fly",
  "Machine Chest Press",
  "Neutral Grip Chest Press Machine",
  "Pec Deck",
  "Pec Deck Machine",
  "Plate Loaded Chest Press",
  "Push Ups",
  "Single Arm Cable Chest Fly",
  "Single Arm Cable Fly",
  "Single Arm Chest Fly Machine",
  "Single Arm Decline Fly",
  "Single Arm Dumbbell Bench Press",
  "Single Arm Dumbbell Fly",
  "Single Arm Incline Fly",
  "Single Arm Machine Chest Press",
  "Smith Machine Bench Press",
  "Standing Cable Fly",
  "Svend Press",
  "Wide Grip Bench Press",

  // ——— Back ———
  "Assisted Pull Up",
  "Back Extension",
  "Barbell Row",
  "Barbell Shrug",
  "Cable Pullover",
  "Chest Supported Dumbbell Row",
  "Close Grip Lat Pulldown",
  "Deadlift",
  "Dumbbell Pullover",
  "Dumbbell Row",
  "Face Pull",
  "Hyperextension",
  "Inverted Row",
  "Kroc Row",
  "Lat Pulldown",
  "Lat Pull Overs",
  "Lat Pullover Machine",
  "Low Cable Row",
  "Machine High Row",
  "Machine Low Row",
  "Machine Row",
  "Meadows Row",
  "Neutral Grip Lat Pulldown",
  "One Arm Cable Row",
  "One Arm Dumbbell Row",
  "One Arm Lat Pulldown",
  "Pendlay Row",
  "Pull Downs",
  "Pull Ups",
  "Rear Delt Fly",
  "Reverse Fly Machine",
  "Rope Pull Down",
  "Seal Row",
  "Seated Cable Row",
  "Seated Row Machine",
  "Shrugs",
  "Single Arm Cable Pulldown",
  "Single Arm Cable Row",
  "Single Arm Dumbbell Row",
  "Single Arm Lat Pulldown",
  "Straight Arm Cable Pulldown",
  "Straight Arm Lat Pulldown",
  "Sumo Deadlift",
  "Supinated Lat Pulldown",
  "T-Bar Row",
  "Trap Bar Deadlift",
  "Upright Row",
  "Wide Grip Lat Pulldown",

  // ——— Shoulders ———
  "Behind Neck Press",
  "Cable Front Raise",
  "Cable Lateral Raise",
  "Cable Rear Delt Fly",
  "Cable Upright Row",
  "Cuban Press",
  "Dumbbell Front Raise",
  "Dumbbell Lateral Raise",
  "Dumbbell Reverse Fly",
  "Dumbbell Shoulder Press",
  "Front Raises",
  "Front Raise Single Arm",
  "Landmine Shoulder Press",
  "Lateral Raise Single Arm",
  "Lateral Raises",
  "Leaning Cable Lateral Raise",
  "Machine Lateral Raise",
  "Machine Reverse Fly",
  "Machine Shoulder Press",
  "Military Press",
  "Overhead Press",
  "Prone Rear Delt Fly",
  "Push Press",
  "Rear Delt Fly Machine",
  "Reverse Cable Fly",
  "Reverse Pec Deck",
  "Seated Dumbbell Shoulder Press",
  "Seated Shoulder Press Machine",
  "Shoulder Press",
  "Smith Machine Shoulder Press",
  "Standing Military Press",
  "Standing Overhead Press",

  // ——— Biceps ———
  "Barbell Curl",
  "Bayesian Curl",
  "Bicep Curl",
  "Cable Curl",
  "Concentration Curl",
  "Cross Body Hammer Curl",
  "Drag Curl",
  "Dumbbell Curl",
  "EZ Bar Curl",
  "Hammer Curl",
  "High Cable Curl",
  "Incline Dumbbell Curl",
  "Machine Curl",
  "One Arm Cable Curl",
  "One Arm Dumbbell Curl",
  "One Arm Preacher Curl",
  "Pinwheel Curl",
  "Preacher Curl",
  "Reverse Curl",
  "Single Arm Cable Curl",
  "Spider Curl",
  "Waiter Curl",
  "Zottman Curl",

  // ——— Triceps ———
  "Cable Overhead Extension",
  "Cable Tricep Pushdown",
  "Close Grip Bench Press",
  "Diamond Push Up",
  "Dips",
  "Kickbacks",
  "Lying Tricep Extension",
  "Machine Dip",
  "One Arm Cable Pushdown",
  "One Arm Overhead Extension",
  "One Handed Tricep Push Down",
  "Overhead Tricep Extensions",
  "Rope Pushdown",
  "Skull Crushers",
  "Single Arm Cable Kickback",
  "Tricep Dip Machine",
  "Tricep Dips",
  "Tricep Extension",
  "Tricep Pushdown",

  // ——— Legs ——— quads / compound
  "Barbell Front Squat",
  "Barbell Squat",
  "Box Squat",
  "Bulgarian Split Squat",
  "Goblet Squat",
  "Hack Squat",
  "Hack Squat Machine",
  "Landmine Squat",
  "Leg Extension",
  "Leg Extension Machine",
  "Leg Press",
  "Leg Press Machine",
  "Pendulum Squat",
  "Single Leg Extension",
  "Single Leg Hack Squat",
  "Single Leg Leg Press",
  "Single Leg Press",
  "Smith Machine Squat",
  "Sissy Squat",
  "Squat",
  "Squat Machine",
  "V Squat",

  // ——— Hamstrings / glutes ———
  "Glute Bridge",
  "Glute Bridge Single Leg",
  "Good Morning",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Hip Thrust",
  "Hyperextension",
  "Leg Curl",
  "Leg Curl Machine",
  "Lying Leg Curl",
  "Nordic Curl",
  "Romanian Deadlift",
  "Seated Leg Curl",
  "Single Leg Curl",
  "Single Leg Deadlift",
  "Single Leg Hip Thrust",
  "Single Leg RDL",
  "Standing Leg Curl",
  "Stiff Leg Deadlift",

  // ——— Lunges / unilateral legs ———
  "Curtsy Lunge",
  "Deficit Lunge",
  "Dumbbell Lunge",
  "Forward Lunge",
  "Lateral Lunge",
  "Lunges",
  "Reverse Lunge",
  "Split Squat",
  "Walking Lunges",

  // ——— Calves ———
  "Calf Raise",
  "Donkey Calf Raise",
  "Leg Press Calf Raise",
  "Seated Calf Raise",
  "Single Leg Calf Raise",
  "Smith Machine Calf Raise",
  "Standing Calf Raise",

  // ——— Core / misc ———
  "Ab Wheel Rollout",
  "Cable Crunch",
  "Hanging Leg Raise",
  "Pallof Press",
  "Plank",
  "Russian Twist",
  "Side Plank",
];

function normalizeDedupe(names: string[]): string[] {
  const seen = new Map<string, string>();
  for (const n of names) {
    const t = n.trim();
    if (!t) continue;
    const low = t.toLowerCase();
    if (!seen.has(low)) seen.set(low, t);
  }
  return [...seen.values()].sort((a, b) => a.localeCompare(b));
}

export const EXERCISE_SUGGESTIONS: string[] = normalizeDedupe(RAW_EXERCISES);

export function filterExerciseSuggestions(query: string, limit = 15): string[] {
  if (!query.trim()) return EXERCISE_SUGGESTIONS.slice(0, limit);
  const q = query.toLowerCase().trim();
  return EXERCISE_SUGGESTIONS.filter((name) => name.toLowerCase().includes(q)).slice(0, limit);
}
