/**
 * Built-in recommended recipes. Calories = round(4×protein + 4×carbs + 9×fats) kcal
 * so totals match the displayed macros (Atwater general factors).
 */

export interface Recipe {
  id: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  sugar?: number;
  sodium?: number;
  fiber?: number;
  description: string;
  category: string;
  prepTime?: string;
  servings?: number;
  /** Built-in recipes always include these; personal saved recipes may omit */
  ingredients?: string[];
  steps?: string[];
}

export function kcalFromMacros(protein: number, carbs: number, fats: number): number {
  return Math.round(protein * 4 + carbs * 4 + fats * 9);
}

const PHOTO_IDS = new Set([
  "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
]);

export function recipeCardImageSrc(recipeId: string): string | null {
  return PHOTO_IDS.has(recipeId) ? `/images/recipes/${recipeId}.png` : null;
}

function r(
  base: Omit<Recipe, "calories"> & { protein: number; carbs: number; fats: number }
): Recipe {
  const { protein, carbs, fats, ...rest } = base;
  return {
    ...rest,
    protein,
    carbs,
    fats,
    calories: kcalFromMacros(protein, carbs, fats),
  };
}

export const recommendedRecipes: Recipe[] = [
  r({
    id: "1",
    name: "Grilled Chicken Salad",
    protein: 35,
    carbs: 15,
    fats: 18,
    sugar: 5,
    sodium: 400,
    fiber: 4,
    description: "Fresh mixed greens with grilled chicken breast, cherry tomatoes, and olive oil dressing",
    category: "Chicken",
    prepTime: "~25 min",
    ingredients: [
      "6 oz grilled chicken breast, sliced",
      "3 cups mixed greens",
      "1 cup cherry tomatoes, halved",
      "½ cucumber, sliced",
      "2 Tbsp extra-virgin olive oil",
      "1 Tbsp lemon juice",
      "1 tsp Dijon mustard",
      "Salt and black pepper",
    ],
    steps: [
      "Season chicken and grill or pan-sear until 165°F internal; rest 5 minutes, then slice.",
      "Whisk olive oil, lemon juice, mustard, salt, and pepper for dressing.",
      "Toss greens, tomatoes, and cucumber in a large bowl.",
      "Top with chicken, drizzle dressing, and serve.",
    ],
  }),
  r({
    id: "12",
    name: "Chicken and Brown Rice",
    protein: 38,
    carbs: 48,
    fats: 10,
    sugar: 2,
    sodium: 450,
    fiber: 5,
    description: "Grilled chicken breast with brown rice and steamed broccoli",
    category: "Chicken",
    prepTime: "~35 min",
    ingredients: [
      "6 oz chicken breast",
      "1 cup cooked brown rice",
      "1½ cups broccoli florets",
      "1 tsp olive oil",
      "Garlic powder, paprika, salt, pepper",
    ],
    steps: [
      "Cook brown rice according to package; keep warm.",
      "Steam broccoli until bright green and tender-crisp.",
      "Season chicken and cook in oiled pan until done; slice.",
      "Plate rice, broccoli, and chicken; season to taste.",
    ],
  }),
  r({
    id: "13",
    name: "Chicken Teriyaki Bowl",
    protein: 36,
    carbs: 52,
    fats: 8,
    sugar: 14,
    sodium: 680,
    fiber: 4,
    description: "Grilled teriyaki chicken with jasmine rice and vegetables",
    category: "Chicken",
    prepTime: "~30 min",
    ingredients: [
      "6 oz chicken thigh or breast, cubed",
      "1 cup cooked jasmine rice",
      "½ bell pepper, strips",
      "½ cup snap peas",
      "¼ cup low-sodium teriyaki sauce",
      "1 tsp sesame oil",
      "Sesame seeds, sliced scallions",
    ],
    steps: [
      "Cook rice; prep vegetables.",
      "Stir-fry chicken in sesame oil until nearly cooked through.",
      "Add vegetables; cook until tender. Add teriyaki; glaze 1–2 minutes.",
      "Serve over rice; garnish with sesame and scallions.",
    ],
  }),
  r({
    id: "14",
    name: "Chicken Caesar Wrap",
    protein: 32,
    carbs: 38,
    fats: 14,
    sugar: 4,
    sodium: 720,
    fiber: 5,
    description: "Grilled chicken, romaine lettuce, parmesan, and caesar dressing in a whole wheat wrap",
    category: "Chicken",
    prepTime: "~20 min",
    ingredients: [
      "5 oz grilled chicken, sliced",
      "1 large whole wheat tortilla",
      "1½ cups chopped romaine",
      "2 Tbsp shaved parmesan",
      "2 Tbsp light Caesar dressing",
      "Cracked black pepper",
    ],
    steps: [
      "Warm tortilla briefly.",
      "Toss romaine with dressing and parmesan.",
      "Layer chicken and salad on tortilla; roll tightly.",
      "Halve diagonally and serve.",
    ],
  }),
  r({
    id: "15",
    name: "Lemon Herb Chicken",
    protein: 34,
    carbs: 12,
    fats: 14,
    sugar: 3,
    sodium: 380,
    fiber: 3,
    description: "Baked chicken breast with lemon, herbs, and roasted vegetables",
    category: "Chicken",
    prepTime: "~40 min",
    ingredients: [
      "6 oz chicken breast",
      "1 lemon (zest + 2 Tbsp juice)",
      "1 tsp olive oil",
      "1 tsp dried oregano or Italian herbs",
      "1 cup zucchini or mixed veg, chunked",
      "Salt and pepper",
    ],
    steps: [
      "Heat oven to 400°F.",
      "Rub chicken with oil, lemon zest, herbs, salt, and pepper.",
      "Roast chicken and vegetables 22–28 minutes until chicken hits 165°F.",
      "Squeeze lemon juice over before serving.",
    ],
  }),
  r({
    id: "2",
    name: "Salmon with Quinoa",
    protein: 32,
    carbs: 35,
    fats: 18,
    sugar: 3,
    sodium: 350,
    fiber: 5,
    description: "Baked salmon fillet served with quinoa and steamed vegetables",
    category: "Protein",
    prepTime: "~30 min",
    ingredients: [
      "5–6 oz salmon fillet",
      "¾ cup cooked quinoa",
      "1 cup broccoli or mixed vegetables",
      "1 tsp olive oil",
      "Lemon wedge, garlic powder, salt, pepper",
    ],
    steps: [
      "Cook quinoa; steam vegetables.",
      "Season salmon; bake at 400°F until flaky (about 12–14 min).",
      "Plate quinoa and vegetables with salmon.",
      "Finish with lemon.",
    ],
  }),
  r({
    id: "10",
    name: "Baked Cod with Sweet Potato",
    protein: 30,
    carbs: 42,
    fats: 8,
    sugar: 12,
    sodium: 320,
    fiber: 7,
    description: "Oven-baked cod fillet with roasted sweet potato and green beans",
    category: "Protein",
    prepTime: "~35 min",
    ingredients: [
      "5–6 oz cod fillet",
      "1 medium sweet potato, cubed",
      "1 cup green beans",
      "1½ tsp olive oil",
      "Paprika, garlic powder, salt, pepper",
      "Lemon wedge",
    ],
    steps: [
      "Toss sweet potato with half the oil; roast at 425°F until tender.",
      "Season cod; bake until opaque and flaky.",
      "Sauté or steam green beans with remaining oil.",
      "Plate together; squeeze lemon over fish.",
    ],
  }),
  r({
    id: "5",
    name: "Turkey Wrap",
    protein: 28,
    carbs: 42,
    fats: 12,
    sugar: 5,
    sodium: 680,
    fiber: 6,
    description: "Whole wheat wrap with lean turkey, avocado, lettuce, and tomato",
    category: "Protein",
    prepTime: "~15 min",
    ingredients: [
      "1 large whole wheat tortilla",
      "4 oz sliced lean turkey breast",
      "¼ avocado, sliced",
      "Lettuce and sliced tomato",
      "1 Tbsp Greek yogurt or light mayo",
      "Thin red onion (optional)",
    ],
    steps: [
      "Spread yogurt or mayo on tortilla.",
      "Layer turkey, avocado, lettuce, tomato, and onion.",
      "Roll tightly; slice in half.",
    ],
  }),
  r({
    id: "16",
    name: "Tuna Poke Bowl",
    protein: 30,
    carbs: 45,
    fats: 10,
    sugar: 6,
    sodium: 520,
    fiber: 4,
    description: "Fresh tuna, brown rice, edamame, avocado, and sesame dressing",
    category: "Protein",
    prepTime: "~25 min",
    ingredients: [
      "5 oz sushi-grade tuna, cubed",
      "1 cup cooked brown rice",
      "½ cup shelled edamame",
      "¼ avocado, cubed",
      "Cucumber slices, shredded carrot",
      "1 Tbsp low-sodium soy sauce, 1 tsp sesame oil",
      "Sesame seeds, scallions",
    ],
    steps: [
      "Toss tuna lightly with half the soy and a little sesame oil.",
      "Warm or cool rice as you like; layer in a bowl.",
      "Arrange tuna, edamame, avocado, and veg in sections.",
      "Drizzle remaining soy and sesame oil; top with seeds and scallions.",
    ],
  }),
  r({
    id: "17",
    name: "Beef Stir Fry",
    protein: 35,
    carbs: 38,
    fats: 14,
    sugar: 8,
    sodium: 580,
    fiber: 5,
    description: "Lean beef strips with mixed vegetables in a light soy-ginger sauce",
    category: "Protein",
    prepTime: "~25 min",
    ingredients: [
      "6 oz lean beef sirloin, sliced thin",
      "2 cups mixed stir-fry vegetables",
      "1 cup cooked brown rice or noodles",
      "2 Tbsp low-sodium stir-fry sauce",
      "1 tsp fresh ginger, 1 garlic clove",
      "1 tsp cornstarch mixed with 2 Tbsp water (optional slurry)",
    ],
    steps: [
      "Stir-fry beef on high heat until browned; remove.",
      "Cook ginger, garlic, and vegetables until crisp-tender.",
      "Return beef; add sauce and slurry; toss until glossy.",
      "Serve over rice or noodles.",
    ],
  }),
  r({
    id: "6",
    name: "Vegetable Stir Fry",
    protein: 15,
    carbs: 38,
    fats: 10,
    sugar: 8,
    sodium: 520,
    fiber: 7,
    description: "Mixed vegetables stir-fried with tofu in a light soy sauce",
    category: "Vegetarian",
    prepTime: "~20 min",
    ingredients: [
      "6 oz firm tofu, cubed",
      "3 cups mixed vegetables (broccoli, peppers, carrots)",
      "1 Tbsp low-sodium soy sauce",
      "1 tsp sesame oil",
      "1 garlic clove, 1 tsp ginger",
      "1 cup cooked brown rice",
    ],
    steps: [
      "Press tofu; pan-sear until golden.",
      "Stir-fry vegetables with garlic and ginger.",
      "Add tofu and soy sauce; toss 1 minute.",
      "Finish with sesame oil; serve over rice.",
    ],
  }),
  r({
    id: "9",
    name: "Quinoa Bowl",
    protein: 18,
    carbs: 58,
    fats: 12,
    sugar: 6,
    sodium: 380,
    fiber: 9,
    description: "Quinoa base with black beans, corn, avocado, and salsa",
    category: "Vegetarian",
    prepTime: "~25 min",
    ingredients: [
      "1 cup cooked quinoa",
      "½ cup black beans, drained",
      "⅓ cup corn kernels",
      "¼ avocado, diced",
      "¼ cup salsa",
      "Lime juice, cumin, salt",
      "Fresh cilantro (optional)",
    ],
    steps: [
      "Warm beans and corn with a pinch of cumin.",
      "Layer quinoa in a bowl.",
      "Top with beans, corn, avocado, and salsa.",
      "Squeeze lime; garnish with cilantro.",
    ],
  }),
  r({
    id: "18",
    name: "Mediterranean Bowl",
    protein: 16,
    carbs: 48,
    fats: 16,
    sugar: 8,
    sodium: 420,
    fiber: 10,
    description: "Chickpeas, cucumber, tomatoes, olives, feta cheese, and tahini",
    category: "Vegetarian",
    prepTime: "~15 min",
    ingredients: [
      "1 cup cooked quinoa or couscous",
      "½ cup chickpeas",
      "½ cup chopped cucumber and tomato",
      "5 kalamata olives, pitted",
      "1 oz feta, crumbled",
      "1 Tbsp tahini + 1 Tbsp lemon juice + water to thin",
    ],
    steps: [
      "Whisk tahini, lemon, and water for dressing.",
      "Warm chickpeas if you like.",
      "Layer grain, chickpeas, vegetables, olives, and feta.",
      "Drizzle dressing over the top.",
    ],
  }),
  r({
    id: "19",
    name: "Veggie Burger",
    protein: 18,
    carbs: 42,
    fats: 12,
    sugar: 6,
    sodium: 580,
    fiber: 8,
    description: "Plant-based patty with lettuce, tomato, and whole grain bun",
    category: "Vegetarian",
    prepTime: "~20 min",
    ingredients: [
      "1 whole grain burger bun",
      "1 plant-based or homemade veggie patty",
      "1 slice cheese (optional)",
      "Lettuce, tomato, onion",
      "1 Tbsp ketchup or mustard",
    ],
    steps: [
      "Cook patty per package until heated through and crisp on edges.",
      "Toast bun lightly.",
      "Layer patty, cheese if using, and toppings.",
      "Add condiments and serve.",
    ],
  }),
  r({
    id: "20",
    name: "Lentil Curry",
    protein: 20,
    carbs: 52,
    fats: 6,
    sugar: 8,
    sodium: 480,
    fiber: 15,
    description: "Spiced red lentils with basmati rice and naan",
    category: "Vegetarian",
    prepTime: "~35 min",
    ingredients: [
      "¾ cup dry red lentils",
      "1 cup light coconut milk + 1 cup water",
      "1 Tbsp curry powder or paste",
      "1 cup spinach",
      "½ cup cherry tomatoes",
      "1 small onion, diced",
      "1 cup cooked basmati rice",
    ],
    steps: [
      "Sauté onion until soft; add spices 30 seconds.",
      "Add lentils, coconut milk, and water; simmer 18–22 minutes until soft.",
      "Stir in spinach and tomatoes; wilt 2 minutes.",
      "Serve with rice (and naan if desired).",
    ],
  }),
  r({
    id: "3",
    name: "Greek Yogurt Parfait",
    protein: 20,
    carbs: 35,
    fats: 8,
    sugar: 22,
    sodium: 120,
    fiber: 4,
    description: "Layered Greek yogurt with fresh berries, granola, and honey",
    category: "Breakfast",
    prepTime: "~10 min",
    ingredients: [
      "1 cup nonfat Greek yogurt",
      "½ cup mixed berries",
      "⅓ cup low-sugar granola",
      "1 tsp honey",
    ],
    steps: [
      "Spoon half the yogurt into a glass.",
      "Add half the berries and granola.",
      "Repeat layers; drizzle honey on top.",
    ],
  }),
  r({
    id: "4",
    name: "Oatmeal with Berries",
    protein: 12,
    carbs: 55,
    fats: 8,
    sugar: 18,
    sodium: 150,
    fiber: 8,
    description: "Steel-cut oats topped with mixed berries, almonds, and a drizzle of honey",
    category: "Breakfast",
    prepTime: "~20 min",
    ingredients: [
      "½ cup dry steel-cut or rolled oats",
      "1½ cups water or milk",
      "½ cup mixed berries",
      "1 Tbsp sliced almonds",
      "1 tsp honey",
      "Pinch cinnamon",
    ],
    steps: [
      "Cook oats in water or milk per package until creamy.",
      "Top with berries, almonds, cinnamon, and honey.",
    ],
  }),
  r({
    id: "8",
    name: "Egg White Scramble",
    protein: 24,
    carbs: 8,
    fats: 10,
    sugar: 3,
    sodium: 420,
    fiber: 2,
    description: "Scrambled egg whites with spinach, mushrooms, and whole grain toast",
    category: "Breakfast",
    prepTime: "~15 min",
    ingredients: [
      "1 cup liquid egg whites (about 8 whites)",
      "1 cup spinach",
      "½ cup sliced mushrooms",
      "1 slice whole grain toast",
      "Cooking spray, salt, pepper",
    ],
    steps: [
      "Sauté mushrooms until browned; add spinach to wilt.",
      "Pour in egg whites; scramble gently until set.",
      "Serve with toast.",
    ],
  }),
  r({
    id: "21",
    name: "Avocado Toast",
    protein: 10,
    carbs: 32,
    fats: 16,
    sugar: 4,
    sodium: 380,
    fiber: 12,
    description: "Whole grain toast with mashed avocado, poached egg, and cherry tomatoes",
    category: "Breakfast",
    prepTime: "~15 min",
    ingredients: [
      "1 slice thick whole grain bread",
      "½ ripe avocado",
      "1 poached or fried egg",
      "½ cup halved cherry tomatoes",
      "Red pepper flakes, salt, pepper",
    ],
    steps: [
      "Toast bread until crisp.",
      "Mash avocado with salt and pepper; spread on toast.",
      "Top with egg and tomatoes; sprinkle chili flakes.",
    ],
  }),
  r({
    id: "22",
    name: "Protein Pancakes",
    protein: 28,
    carbs: 38,
    fats: 8,
    sugar: 12,
    sodium: 320,
    fiber: 6,
    description: "Protein-rich pancakes with Greek yogurt and fresh fruit",
    category: "Breakfast",
    prepTime: "~20 min",
    ingredients: [
      "1 scoop protein powder",
      "½ cup oat flour or blended oats",
      "2 eggs",
      "¼ cup milk",
      "1 tsp baking powder",
      "¼ cup Greek yogurt and berries to serve",
    ],
    steps: [
      "Blend or whisk dry ingredients; whisk in eggs and milk.",
      "Cook pancakes on a nonstick griddle over medium heat.",
      "Stack and top with yogurt and berries.",
    ],
  }),
  r({
    id: "7",
    name: "Protein Smoothie",
    protein: 25,
    carbs: 28,
    fats: 4,
    sugar: 20,
    sodium: 80,
    fiber: 4,
    description: "Banana, spinach, protein powder, and almond milk blend",
    category: "Snacks",
    prepTime: "~5 min",
    ingredients: [
      "1 scoop protein powder",
      "1 banana, frozen or fresh",
      "1 cup spinach",
      "1 cup unsweetened almond milk",
      "Ice (optional)",
    ],
    steps: [
      "Add all ingredients to a blender.",
      "Blend until smooth; add ice for thickness if you like.",
    ],
  }),
  r({
    id: "11",
    name: "Cottage Cheese Bowl",
    protein: 22,
    carbs: 15,
    fats: 6,
    sugar: 10,
    sodium: 380,
    fiber: 1,
    description: "Low-fat cottage cheese with fresh peaches and a sprinkle of cinnamon",
    category: "Snacks",
    prepTime: "~5 min",
    ingredients: [
      "1 cup low-fat cottage cheese",
      "1 small peach or nectarine, sliced",
      "¼ tsp cinnamon",
      "1 Tbsp chopped nuts (optional)",
    ],
    steps: [
      "Scoop cottage cheese into a bowl.",
      "Top with fruit, cinnamon, and nuts.",
    ],
  }),
  r({
    id: "23",
    name: "Protein Bar",
    protein: 20,
    carbs: 22,
    fats: 8,
    sugar: 14,
    sodium: 180,
    fiber: 4,
    description: "Homemade protein bar with nuts, dates, and chocolate",
    category: "Snacks",
    prepTime: "~30 min + chill",
    ingredients: [
      "1 cup pitted dates, softened",
      "½ cup mixed nuts, chopped",
      "2 scoops protein powder",
      "2 Tbsp cocoa powder",
      "2–3 Tbsp water as needed",
    ],
    steps: [
      "Pulse dates in a food processor until sticky.",
      "Add nuts, protein powder, cocoa; pulse until combined (add water sparingly).",
      "Press into a lined pan; refrigerate 1 hour.",
      "Cut into bars; store chilled.",
    ],
  }),
  r({
    id: "24",
    name: "Hummus & Veggies",
    protein: 8,
    carbs: 22,
    fats: 8,
    sugar: 4,
    sodium: 320,
    fiber: 8,
    description: "Fresh hummus with carrot sticks, cucumber, and bell peppers",
    category: "Snacks",
    prepTime: "~10 min",
    ingredients: [
      "½ cup prepared or homemade hummus",
      "1 carrot, cut into sticks",
      "½ cucumber, sliced",
      "½ bell pepper, strips",
    ],
    steps: [
      "Arrange hummus in a small bowl.",
      "Wash and cut vegetables.",
      "Dip and enjoy.",
    ],
  }),
];
